FROM debian:bookworm-slim

ENV MODELS_DIR=/models \
    SHARED_MODELS_DIR=/shared-models

WORKDIR /bundle

COPY model ./models
COPY docker/copy_models.sh /usr/local/bin/copy_models.sh

RUN chmod +x /usr/local/bin/copy_models.sh

CMD ["/usr/local/bin/copy_models.sh"]
